# Generated by Django 5.1.5 on 2025-01-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(default='not indicated', max_length=100, null=True),
        ),
    ]
